/**
 * Keeps track of the amount of milk produced in liters and computes
 * the number of cartons of milk that can be sold and the amount of
 * profit gained by selling the cartons.
 *
 * @author Shaine O'Neal
 * @version 1.0
 */

public class MilkManager {
    final private double conversion = 3.78;
    private double amtMilkInLiters, prodCostPerLiter, cartonSalePrice;

    /**
     * Constructor for MilkManager class
     *
     * @param amtMilkInLiters       amount of milk in liters
     * @param prodCostPerLiter      cost of production per liter
     * @param cartonSalePrice       final sale price of one carton
     *
     * @pre amtMilkInLiters, prodCostPerLiter, and cartonSalePrice
     *      != null
     * @post none
     */

    public MilkManager(double amtMilkInLiters, double prodCostPerLiter, double cartonSalePrice) {

    }

    /**
     * Returns the total number of cartons of milk produced
     *
     * @return number of cartons produced
     *
     * @pre none
     * @post none
     */

    public int numCartonsProduced(){
        return 0;
    }

    /**
     * Returns profit generated by selling the cartons produced after considering our production costs
     *
     * @pre none
     * @post final number must be in currency format
     */

    public double computeProfit(){
        return 0;
    }
}
